FROM python:3.8.16-slim-bullseye
WORKDIR /testwork
#ADD routes.txt /testwork/routes.txt
ADD requirements.txt /testwork/requirements.txt
ADD service/ /testwork/service
RUN python3 -m pip install --no-cache-dir -U -r requirements.txt
CMD ["python3", "-m", "service"]