---
# ConfigMap for routes data
apiVersion: v1
kind: ConfigMap
metadata:
  name: routing-table-data
  namespace: default
data:
  # In production, use a PersistentVolume or external storage
  # For testing, routes.txt would be mounted from host or built into image
---
# Deployment for the Routing Table API
apiVersion: apps/v1
kind: Deployment
metadata:
  name: routing-table-api
  namespace: default
  labels:
    app: routing-table-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: routing-table-api
  template:
    metadata:
      labels:
        app: routing-table-api
    spec:
      containers:
      - name: api
        image: routing-table-api:latest
        imagePullPolicy: Never  # Use local image for testing
        ports:
        - containerPort: 5000
          name: http
          protocol: TCP
        volumeMounts:
        - name: routes-data
          mountPath: /app/routes.txt
          subPath: routes.txt
          readOnly: true
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 20
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "2000m"
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: PROC_NUM
          value: "4"
        - name: HOST
          value: "0.0.0.0"
        - name: PORT
          value: "5000"
      volumes:
      - name: routes-data
        hostPath:
          path: /path/to/routing-table-api/routes.txt  # Update to actual path
          type: File
---
# Service to expose the API
apiVersion: v1
kind: Service
metadata:
  name: routing-table-api
  namespace: default
  labels:
    app: routing-table-api
spec:
  type: ClusterIP
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
    name: http
  selector:
    app: routing-table-api
---
# Job for running tests
apiVersion: batch/v1
kind: Job
metadata:
  name: routing-table-api-tests
  namespace: default
  labels:
    app: routing-table-api-tests
spec:
  backoffLimit: 2
  template:
    metadata:
      labels:
        app: routing-table-api-tests
    spec:
      restartPolicy: Never
      containers:
      - name: tests
        image: routing-table-api:test
        imagePullPolicy: Never  # Use local image for testing
        env:
        - name: API_URL
          value: "http://routing-table-api:5000"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      initContainers:
      - name: wait-for-api
        image: busybox:1.36
        command:
        - sh
        - -c
        - |
          until wget -q --spider http://routing-table-api:5000/health; do
            echo "Waiting for API to be ready..."
            sleep 5
          done
          echo "API is ready!"
---
# Optional: Ingress for external access (requires Ingress controller)
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: routing-table-api
#   namespace: default
#   annotations:
#     nginx.ingress.kubernetes.io/rewrite-target: /
# spec:
#   rules:
#   - host: routing-api.local
#     http:
#       paths:
#       - path: /
#         pathType: Prefix
#         backend:
#           service:
#             name: routing-table-api
#             port:
#               number: 5000
